# Generated by Django 2.2.12 on 2022-07-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=15)),
                ('transaction_charge', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('Bank_account_name', models.CharField(max_length=15)),
                ('Bank_account_number', models.CharField(max_length=15)),
                ('balance', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('date_created', models.DateField()),
                ('pin', models.SmallIntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
