# Generated by Django 4.0.6 on 2022-08-01 18:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.SmallIntegerField()),
                ('account_name', models.CharField(max_length=10)),
                ('deposit', models.PositiveIntegerField()),
                ('withdrawals', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=8)),
                ('expiry_date', models.DateTimeField()),
                ('card_type', models.CharField(max_length=6)),
                ('date_issued', models.DateTimeField()),
                ('issuer', models.CharField(max_length=6)),
                ('secuity_code', models.SmallIntegerField()),
                ('signature', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, null=True)),
                ('nationality', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField()),
                ('bill_number', models.PositiveIntegerField()),
                ('receipt_file', models.FileField(upload_to='')),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='employment_status',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='Points',
            new_name='bonus',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='Date_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_charge',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='Bank_account_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='Bank_account_number',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Third_Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('user_id', models.PositiveSmallIntegerField(null=True)),
                ('transaction_cost', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('location', models.CharField(max_length=10)),
                ('isActive', models.BooleanField(max_length=3)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=12, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('status', models.CharField(max_length=12)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=10)),
                ('balance', models.IntegerField()),
                ('payment_due_date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('datetime', models.DateTimeField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.currency'),
        ),
    ]
