# Generated by Django 4.1 on 2022-08-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20220825_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=8)),
                ('expiry_date', models.DateTimeField()),
                ('card_type', models.CharField(max_length=6)),
                ('date_issued', models.DateTimeField()),
                ('issuer', models.CharField(max_length=15)),
                ('secuity_code', models.SmallIntegerField()),
                ('signature', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Status',
            field=models.CharField(blank=True, default=False, max_length=6),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_Account',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_charge',
            field=models.CharField(blank=True, default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='third_party',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(blank=True, default=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, default=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
