# Generated by Django 4.1 on 2022-09-01 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_alter_account_id_alter_cards_id_alter_currency_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=25, null=True)),
                ('date_issued', models.DateTimeField()),
                ('card_number', models.CharField(max_length=15, null=True)),
                ('signature', models.CharField(max_length=15, null=True)),
                ('expiry_date', models.DateField()),
                ('card_status', models.CharField(max_length=15, null=True)),
                ('security_code', models.PositiveSmallIntegerField()),
                ('issuer', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='date',
            new_name='date_time_received',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_amount',
            new_name='transaction_cost',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='withdrawals',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_date',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='third_party',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='third_party',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='third_party',
            name='location',
        ),
        migrations.RemoveField(
            model_name='third_party',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='origin_Account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_number',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='currency',
            name='country_origin',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='signature',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='duedate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='guaranter',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interestrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanstatus',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loanterm',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='paymentdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification_recipient', to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_transaction', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='reward',
            name='points',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='third_party',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='third_party',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='third_party',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destinations', to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_account_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reward_transaction', to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reward_wallet', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='third_party',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Third_party_account', to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='third_party',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Third_party_currency', to='wallet.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_charge',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_currency', to='wallet.currency'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Card_account', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_account_origin', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
